name: streaming_autoloader_sample
description: ''
version: v1
author: nathan@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: streamingautoloadersample
  parentArtefactID: poc-experian
  buildSystem: wheel
  author: null
  createdAt: '2023-10-02 20:34:52'
pipelines:
  pipelines/L1_prep_data:
    name: L0_PrepData_FirstBatch
    description: This pipeline graph generates sample data for stock analysis, with
      information on the date, stock symbol, analyst, and estimated earnings per share.
      It then repartitions the data into a single partition for efficient processing.
      Finally, it writes the data to a landing zone in CSV format for use in incremental
      ETL processes.
    author: nathan@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-10-02 21:39:10'
    datasets:
      inputs: []
      outputs:
      - datasets/LandingZone
    subgraphs: []
    dependencies: {}
  pipelines/L2_autoloader_read:
    name: L1_WriteToBronze
    description: This pipeline graph reads streaming data from a cloud file source
      in CSV format and loads it into a Delta table in Bronze zone. The schema is
      defined explicitly and a checkpoint location is specified to ensure fault tolerance.
      This enables real-time data processing and analysis for downstream applications.
    author: nathan@prophecy.io
    mode: stream
    artefactID: ''
    language: python
    createdAt: '2023-10-03 01:31:59'
    datasets:
      inputs:
      - datasets/LandingZone_Stream
      outputs:
      - datasets/BronzeTable
    subgraphs: []
    dependencies: {}
  pipelines/L3_StreamtoSilver:
    name: L2_StreamtoSilver
    description: This pipeline reads data from a Delta table in the bronze layer and
      writes it to a Delta table in the silver layer. The checkpoint location is specified
      to ensure fault tolerance and the output mode is set to append to avoid overwriting
      existing data. The pipeline is triggered once to perform the initial load and
      can be scheduled to run periodically for continuous updates.
    author: nathan@prophecy.io
    mode: stream
    artefactID: ''
    language: python
    createdAt: '2023-10-03 02:24:57'
    datasets:
      inputs:
      - datasets/BronzeTable
      outputs:
      - datasets/SilverTable
    subgraphs: []
    dependencies: {}
  pipelines/L1_PrepData_SecondBatch:
    name: L0_PrepData_SecondBatch
    description: 'This pipeline graph generates another set of sample data that will
      be appended to the Landing Zone. That data will be picked up downstream in the
      Bronze and Silver tables. '
    author: nathan@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-10-03 02:41:58'
    datasets:
      inputs: []
      outputs:
      - datasets/LandingZone
    subgraphs: []
    dependencies: {}
  pipelines/Display_Delta_Tables:
    name: Display_Delta_Tables
    description: This pipeline can be used to quickly read and display the data from
      each layer of the pipeline (landing, bronze, silver).
    author: nathan@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-10-03 02:53:09'
    datasets:
      inputs:
      - datasets/L1_BronzeTable
      - datasets/L2_SilverTable
      - datasets/LandingZone
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/LandingZone:
    name: L0_LandingZone
    description: ''
    author: nathan@prophecy.io
    createdAt: '2023-10-03 01:23:27'
    mode: batch
    physicalDatasets:
      DBX_SalesEng:
        fabricId: 4678
        datasetType: File
        description: ''
        author: nathan@prophecy.io
        createdAt: '2023-10-03 01:23:27'
  datasets/LandingZone_Stream:
    name: L0_LandingZone_Stream
    description: ''
    author: nathan@prophecy.io
    createdAt: '2023-10-03 01:36:42'
    mode: stream
    physicalDatasets:
      DBX_SalesEng:
        fabricId: 4678
        datasetType: File
        description: ''
        author: nathan@prophecy.io
        createdAt: '2023-10-03 01:36:42'
  datasets/BronzeTable:
    name: L1_BronzeTable_Stream
    description: ''
    author: nathan@prophecy.io
    createdAt: '2023-10-03 02:11:32'
    mode: stream
    physicalDatasets:
      DBX_SalesEng:
        fabricId: 4678
        datasetType: File
        description: ''
        author: nathan@prophecy.io
        createdAt: '2023-10-03 02:11:32'
  datasets/SilverTable:
    name: L2_SilverTable_Stream
    description: ''
    author: nathan@prophecy.io
    createdAt: '2023-10-03 02:31:46'
    mode: stream
    physicalDatasets:
      DBX_SalesEng:
        fabricId: 4678
        datasetType: File
        description: ''
        author: nathan@prophecy.io
        createdAt: '2023-10-03 02:31:46'
  datasets/L2_SilverTable:
    name: L2_SilverTable
    description: ''
    author: nathan@prophecy.io
    createdAt: '2023-10-03 02:35:09'
    mode: batch
    physicalDatasets:
      DBX_SalesEng:
        fabricId: 4678
        datasetType: File
        description: ''
        author: nathan@prophecy.io
        createdAt: '2023-10-03 02:35:09'
  datasets/L1_BronzeTable:
    name: L1_BronzeTable
    description: ''
    author: nathan@prophecy.io
    createdAt: '2023-10-03 02:45:16'
    mode: batch
    physicalDatasets:
      DBX_SalesEng:
        fabricId: 4678
        datasetType: File
        description: ''
        author: nathan@prophecy.io
        createdAt: '2023-10-03 02:45:16'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.2.0
  gems: {}
functions:
  author: null
  createdAt: '2023-10-02 20:34:52'
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.0.4
    isDefault: true
    author: null
    createdAt: '2023-10-02 20:34:41'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2023-10-02 20:34:41'
  '12656':
    projectUID: 12656
    projectName: ProphecyStreamingPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12656.git&subPath=
    version: 0.0.1
    isDefault: false
    author: null
    createdAt: '2023-10-02 20:53:47'
pipelineConfigurations: {}
